theme: jekyll-theme-cayman
# Knjiznicar

### English description: 
Program will record who borrowed a book and when he/she should return it. It will support viewing of the date when the book was borrowed, borrower could make a reservation for the book he wants to borrow or extend duration of already borrowed book. The Longest period in which the book must be returned will be arranged by the type or frequency of check-outs and number of copies of the book.

User will have an insight in history of borrowed books, list of currently borrowed books and return date. If the user would overdue his deadline, fee would be added to his account.

#### Programs used:
* [IntelliJ IDEA](https://www.jetbrains.com/idea/)
* [Toad Data Modeler 5.4 - Freeware](http://www.toad-data-modeler.com/download/)
* [MySQL Workbench](https://www.mysql.com/products/workbench/)
* [MariaDB](https://mariadb.org/)

### Slovenian description: 
Program bi sledil, kdo si je izposodil knjigo, ter do kdaj jo naj vrne. Prav tako bi bil preko programa možen ogled datuma izposoje,
opravil bi lahko rezervacijo ali podaljšanje izposoje knjig. 
Najdaljši možen čas izposoje knjig bi bil razvrščen glede na vrsto oziroma pogostost izposoje in število izvodov knjige.

Uporabnik bi imel v programu vpogled v zgodovino izposoje knjig, seznam trenutno izposojenih ter datuma vračila.
Če bi uporabnik prekoračil čas, bi se mu pripisala  zamudnina za knjigo.

#### Uporabljeni programi:
* [IntelliJ IDEA](https://www.jetbrains.com/idea/)
* [Toad Data Modeler 5.4 - Freeware](http://www.toad-data-modeler.com/download/)
* [MySQL Workbench](https://www.mysql.com/products/workbench/)
* [MariaDB](https://mariadb.org/)

